

// === Integración Login + Sheets + Folios ===
const GAS_URL = "https://script.google.com/macros/s/AKfycbzqP78PjTMVeHsLnDVylPp-EWIlYsPTN1sA3YamJM0NkkplZLMzcB4keWivN6qH_BtU/exec"; // <-- pega aquí tu URL de Apps Script

function zeroPad(n, size=4){ n = parseInt(n||0,10); return String(n).padStart(size,'0'); }

async function getNextFolio(){
  // Intenta obtener desde Apps Script (opcional)
  if (GAS_URL && GAS_URL.startsWith("https://")) {
    try{
      const r = await fetch(GAS_URL + "?action=nextFolio");
      if(r.ok){
        const j = await r.json();
        if(j && j.folio){ 
          localStorage.setItem("folioLast", j.folio);
          return j.folio;
        }
      }
    }catch(e){ console.warn("No se pudo obtener folio desde GAS:", e); }
  }
  // Fallback local
  let last = parseInt(localStorage.getItem("folioLast")||"0",10) + 1;
  const f = zeroPad(last);
  localStorage.setItem("folioLast", String(last));
  return f;
}


async function sendToSheet({folio, paciente, fecha, usuario}){
  if(!GAS_URL || GAS_URL.includes("https://script.google.com/mac...MzcB4keWivN6qH_BtU/exec")) return; // evitar fallos si no lo configuran
  try {
    await fetch(GAS_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ folio, paciente, fecha, usuario })
    });
  } catch(e){ console.warn("Error enviando a Google Sheets:", e); }
}

// === Payload para guardar cotización NOMAD en Firestore ===
function getCotizacionPayloadNomad(folio){
  try{
    const totalEl = document.getElementById('total');
    const total = totalEl
      ? Number((totalEl.textContent || '').replace(/[^0-9.,-]/g,'').replace(/,/g,'')) || 0
      : 0;

    const pruebas = Array.from(
      document.querySelectorAll('#tablaPruebas tbody tr')
    ).map(tr => {
      const tds = tr.querySelectorAll('td');
      const parse = (txt) =>
        Number((txt || '').replace(/[^0-9.,-]/g,'').replace(/,/g,'')) || 0;

      return {
        prueba:   (tds[0]?.textContent || '').trim(),
        cantidad: parse(tds[1]?.textContent || ''),
        precioUnit: parse(tds[2]?.textContent || ''),
        subtotal: parse(tds[3]?.textContent || '')
      };
    });

    return {
      folio: folio || '',
      fechaEmision: document.getElementById('fechaEmision')?.value || '',
      fechaValidez: document.getElementById('fechaValidez')?.value || '',
      realizadoPor: document.getElementById('realizadoPor')?.value || '',
      paciente: document.getElementById('paciente')?.value || '',
      medico: document.getElementById('medico')?.value || '',
      aseguradora: document.getElementById('aseguradora')?.value || '',
      kam: document.getElementById('kam')?.value || '',
      diagnostico: document.getElementById('diagnostico')?.value || '',
      fechaProgramacion: document.getElementById('fechaProgramacion')?.value || '',
      total,
      pruebas
    };
  }catch(e){
    console.warn('No se pudo construir el payload de cotización NOMAD', e);
    return { folio: folio || '', error: String(e) };
  }
}
// === Datos embebidos (sin fetch) ===
const DATASETS = {"gestion_nomad":[{"nombre":"FoundationOne CDx","precio":95000.0},{"nombre":"FoundationOne Liquid CDx","precio":95000.0},{"nombre":"FoundationOne Heme","precio":116500.0},{"nombre":"Foundation One CDX  Por ti (50% )","precio":47500.00},{"nombre":"Foundation One Liquid Por ti (50% )","precio":47500.00},{"nombre":"Avenio Roche Tisssue","precio":48000.0},{"nombre":"Examen OncoIDX Complete ctDNA","precio":48000.0},{"nombre":"Guardant360 CDx","precio":80270.0},{"nombre":"Guardant360 CDx Expanded","precio":92000.0},{"nombre":"Guardant Health Reveal","precio":83950.0},{"nombre":"Tempus xF","precio":85344.83},{"nombre":"Tempus xF+","precio":85344.83},{"nombre":"Tempus xT","precio":85344.83},{"nombre":"Tempus xT + xR","precio":85344.83},{"nombre":"INVITAE Panel multicancer ","precio":20689.66},{"nombre":"INVITAE Common herditary Cancer","precio":20689.66},{"nombre":"INVITAE Hereditary Breast Cancer STAT Panel","precio":20689.66}],"gestion_comercial":[{"nombre":"FoundationOne CDx","precio":111744.0},{"nombre":"FoundationOne Liquid CDx","precio":111744.0},{"nombre":"FoundationOne Heme","precio":111744.0},{"nombre":"Foundation One CDX  Por ti (50% )","precio":47500.00},{"nombre":"Foundation One Liquid Por ti (50% )","precio":47500.00},{"nombre":"Avenio Roche Tisssue","precio":48000.0},{"nombre":"Examen OncoIDX Complete ctDNA","precio":48000.0},{"nombre":"Guardant360 CDx","precio":101325.0},{"nombre":"Guardant360 CDx Expanded","precio":101325.0},{"nombre":"Guardant Health Reveal","precio":101325.0},{"nombre":"Tempus xF","precio":100000.0},{"nombre":"Tempus xF+","precio":100000.0},{"nombre":"Tempus xT","precio":100000.0},{"nombre":"Tempus xT + xR","precio":100000.0},{"nombre":"INVITAE Panel multicancer ","precio":20689.66},{"nombre":"INVITAE Common herditary Cancer","precio":20689.66},{"nombre":"INVITAE Hereditary Breast Cancer STAT Panel","precio":20689.66}],"gnp":[{"nombre":"FoundationOne CDx","precio":83000.0},{"nombre":"FoundationOne Liquid CDx","precio":83000.0},{"nombre":"FoundationOne Heme","precio":116500.0},{"nombre":"Foundation One CDX  Por ti (50% )","precio":47500.00},{"nombre":"Foundation One Liquid Por ti (50% )","precio":47500.00},{"nombre":"Avenio Roche Tisssue","precio":48000.0},{"nombre":"Examen OncoIDX Complete ctDNA","precio":48000.0},{"nombre":"Guardant360 CDx","precio":80270.0},{"nombre":"Guardant360 CDx Expanded","precio":92000.0},{"nombre":"Guardant Health Reveal","precio":83950.0},{"nombre":"Tempus xF","precio":85344.83},{"nombre":"Tempus xF+","precio":85344.83},{"nombre":"Tempus xT","precio":85344.83},{"nombre":"Tempus xT + xR","precio":85344.83},{"nombre":"INVITAE Panel multicancer ","precio":20689.66},{"nombre":"INVITAE Common herditary Cancer","precio":15517.24},{"nombre":"INVITAE Hereditary Breast Cancer STAT Panel","precio":15517.24}],"dra_genoveva":[{"nombre":"FoundationOne CDx","precio":78300.0},{"nombre":"FoundationOne Liquid CDx","precio":78300.0},{"nombre":"FoundationOne Heme","precio":116500.0},{"nombre":"Foundation One CDX  Por ti (50% )","precio":47500.00},{"nombre":"Foundation One Liquid Por ti (50% )","precio":47500.00},{"nombre":"Avenio Roche Tisssue","precio":48000.0},{"nombre":"Examen OncoIDX Complete ctDNA","precio":48000.0},{"nombre":"Guardant360 CDx","precio":80270.0},{"nombre":"Guardant360 CDx Expanded","precio":92000.0},{"nombre":"Guardant Health Reveal","precio":83950.0},{"nombre":"Tempus xF","precio":85344.83},{"nombre":"Tempus xF+","precio":85344.83},{"nombre":"Tempus xT","precio":85344.83},{"nombre":"Tempus xT + xR","precio":85344.83},{"nombre":"INVITAE Panel multicancer ","precio":20689.66},{"nombre":"INVITAE Common herditary Cancer","precio":20689.66},{"nombre":"INVITAE Hereditary Breast Cancer STAT Panel","precio":20689.66}]};

// === Biomarcadores (desde Excel) ===
const BIOMARCADORES = {"gestion_nomad": [{"nombre": "Biomarcador PDL 1", "precio": 2800.0}, {"nombre": "Biomarcador HRD", "precio": 5180.0}, {"nombre": "Biomarcador MMR", "precio": 5600.0}, {"nombre": "Biomarcador PDY", "precio": 5180.0}, {"nombre": "Biomarcador HER 2", "precio": 3340.0}, {"nombre": "Biomarcador HER2 + FISH", "precio": 6440.0}, {"nombre": "Algorithmic Tumor Origin", "precio": 5600.00}, {"nombre": "MGMT Methylation", "precio": 5600.00}, {"nombre": "UGT1A1", "precio": 5180.00}, {"nombre": "POLE / POLD1", "precio": 2800.00}, {"nombre": "PDL1 SP263 y 22C3", "precio": 2800.00}, {"nombre": "CLDN18", "precio": 5600.00}, {"nombre": "cMET", "precio": 2800.00}, {"nombre": "Biomarcador FOLR1", "precio": 3340.0}], "gestion_comercial": [{"nombre": "Biomarcador PDL 1", "precio": 2800.0}, {"nombre": "Biomarcador HRD", "precio": 5180.0}, {"nombre": "Biomarcador MMR", "precio": 5600.0}, {"nombre": "Biomarcador PDY", "precio": 5180.0}, {"nombre": "Biomarcador HER 2", "precio": 3340.0}, {"nombre": "Biomarcador HER2 + FISH", "precio": 6440.0}, {"nombre": "Algorithmic Tumor Origin", "precio": 5600.00}, {"nombre": "MGMT Methylation", "precio": 5600.00}, {"nombre": "UGT1A1", "precio": 5180.00}, {"nombre": "POLE / POLD1", "precio": 2800.00}, {"nombre": "PDL1 SP263 y 22C3", "precio": 2800.00}, {"nombre": "CLDN18", "precio": 5600.00}, {"nombre": "cMET", "precio": 2800.00}, {"nombre": "Biomarcador FOLR1", "precio": 3340.0}], "gnp": [{"nombre": "Biomarcador PDL 1", "precio": 2800.0}, {"nombre": "Biomarcador HRD", "precio": 5180.0}, {"nombre": "Biomarcador MMR", "precio": 5600.0}, {"nombre": "Biomarcador PDY", "precio": 5180.0}, {"nombre": "Biomarcador HER 2", "precio": 3340.0}, {"nombre": "Biomarcador HER2 + FISH", "precio": 6440.0}, {"nombre": "Algorithmic Tumor Origin", "precio": 5600.00}, {"nombre": "MGMT Methylation", "precio": 5600.00}, {"nombre": "UGT1A1", "precio": 5180.00}, {"nombre": "POLE / POLD1", "precio": 2800.00}, {"nombre": "PDL1 SP263 y 22C3", "precio": 2800.00}, {"nombre": "CLDN18", "precio": 5600.00}, {"nombre": "cMET", "precio": 2800.00}, {"nombre": "Biomarcador FOLR1", "precio": 3340.0}], "dra_genoveva": [{"nombre": "Biomarcador PDL 1", "precio": 2800.0}, {"nombre": "Biomarcador HRD", "precio": 5180.0}, {"nombre": "Biomarcador MMR", "precio": 5600.0}, {"nombre": "Biomarcador PDY", "precio": 5180.0}, {"nombre": "Biomarcador HER 2", "precio": 3340.0}, {"nombre": "Biomarcador HER2 + FISH", "precio": 6440.0}, {"nombre": "Algorithmic Tumor Origin", "precio": 5600.00}, {"nombre": "MGMT Methylation", "precio": 5600.00}, {"nombre": "UGT1A1", "precio": 5180.00}, {"nombre": "POLE / POLD1", "precio": 2800.00}, {"nombre": "PDL1 SP263 y 22C3", "precio": 2800.00}, {"nombre": "CLDN18", "precio": 5600.00}, {"nombre": "cMET", "precio": 2800.00}, {"nombre": "Biomarcador FOLR1", "precio": 3340.0}]};

const MEDICOS = [{"Doctor": "ABEL BERNECHEA MIRANDA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALBERTO VIELMA VALDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALEJANDRA JIMENA GARCÍA VELAZQUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALEJANDRO LOPEZ CUETO ESPINOZA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALFONSO TORRES ROJO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALMA LILIA ORTIZ MALDONADO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ANA CRISTINA ARTEAGA GOMEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ANAIT ABAD SOLARES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "AURORA MEDINA SANSON", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "AZCARY VAZQUEZ TINAJERO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "BENIGNO EMMANUEL RODRIGUEZ SOTO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "BETSABE HERNANDEZ HERNANDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "BRENDA LETICIA GONZALEZ GARCÍA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "CARLOS ALBERTO LARA GUTIÉRREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "CARLOS ALBERTO SERVIN HERNANDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "CARLOS MANUEL ORTIZ MENDOZA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "CRISTINA ALVARADO SILVA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DANTE CARBAJAL OCAMPO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DAVID JOSÉ HEREDIA VÁZQUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DENISSE EUGENIA LEE CERVANTES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DENYS ELIZABETH DELGADO AMADOR", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DIANA PATRICIA JIMENEZ CARRANZA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DINO ALBERTO MURILLO CRUZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EDGAR NERI PAEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EDGAR RODRIGUEZ ANTEZANA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EDNA ROJAS CURIEL", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EDUARDO ANTONIO MAAFS MOLINA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EDUARDO EDMUNDO REYNOSO GOMEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EDUARDO TELLEZ BERNAL", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ELISEO NEFTALI DE LA CRUZ ESCOBAR", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ETZALLI PAMELA LINARES CHAVEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FELIPE VILLEGAS CARLOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FERNANDO CERECEDO DIAZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FERNANDO ULISES LARA GONZÁLEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FERNANDO ULISES LARA MEDINA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GABRIEL GALVAN SALAZAR", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GABRIELA NUÑEZ GUARDADO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GERARDO CASTORENA ROJI", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GERARDO GABRIEL MINAURO MUÑOZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GERMAN CASTELAZO RAMIREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GERMAN CASTELAZO RICO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GLORIA MARTINEZ MARTINEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GUSTAVO JONY RAMOS BLAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "HECTOR ARIAS CEBALLOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "HERMINIA DEL SOCORRO ARVELO SAAVEDRA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "IGNACIO JAIME PEREZ MARTINEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "IRINEO DOMINGUEZ GABRIEL", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "IVÁN ORTIZ CALDERÓN", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JANETT CABALLERO JASSO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JAQUELINE AGUIRRE GOMEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JAVIER GARCIA ESTRADA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JESUS ARMANDO SANCHEZ GONZALEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOEL BAÑUELOS FLORES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JORGE ALBERTO SALAZAR ANDRADE", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE EUGENIO VAZQUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE GERARDO VELAZQUEZ OLGUIN", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE LUIS ALVAREZ VERA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE LUIS LOPEZ LOPEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE MANUEL ARTURO RUANO AGUILAR", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JUAN CARLOS OLIVA POSADA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JUAN CARLOS ZAPOT MARTINEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JUAN FERNANDO ARAGON SANCHEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JUAN LUIS ABOITES LUCERO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JULIO CESAR VELASCO RODRIGUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JULIO EDUARDO MARTÍNEZ SAMANO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "KARINA MURILLO MEDINA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "KELLY GARCIA JAVIER", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LAURA TORRECILLAS TORRES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LIZBETH HANAYANSI FLORES RUIZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LIZBETH VANESSA GARCÍA MONTES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUIIS ANTONIO NUÑEZ TRENADO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUIS JHONATAN BUENO ROSARIO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUZ MARIA RIVAS CORCHADO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MA DE LOURDES GUTIERREZ RIVERA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARCOS LOPEZ NAVEDA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIA DE LA LUZ GARCA TINOCO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARÍA DEL CONSUELO DÍAZ ROMERO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIA ELISA OTEIRO CERDEIRA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIA EUGENIA SALINAS NIEVES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIA PAULA HERNANDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIA TERESA CERVANTES DIAZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIANA MONSERRAT GOMEZ JARA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARISOL RIVERA HERNANDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MIGUEL ANGEL MONROY RAMÍREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MIGUEL NORIEGA JUAREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MOISES ZEFERINO TOQUERO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "NATIVIDAD NERI MUÑOZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "NOE FLORES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "NORA MARIA PEREZ HRNANDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "OSCAR SALVADOR SANCHEZ VELAZQUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "PAMELA AYALA HERNANDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "PATRICIA PADILLA ARRIETA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "PEDRO LUNA MERLOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "PEDRO LUNA PEREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "RAFAEL MEDRANO GUZMAN", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "RAMON JESUS MARTELL GUERRERO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ROSA LUZ LUNA PLACENCIA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SALIM ABRAHAM BARQUET MUÑOZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SEIR ALFONSO CORTES CARDENAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SERGIO PEDRAZA BARAJAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SIGMUND RODRIGUEZ ROJAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SILVIA MARGARITA ALVARFEZ MALDONADO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "TALINA RAMIREZ CARO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "VICTOR ALFONSO MARTINEZ DIAZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "VICTOR HUGO CARMONA ORNELA S", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "VICTOR MANUEL MARROQUÍN TORRES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "VICTOR RAMON ANDRADE SEPULVEDA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "XINOTECATL JIMENEZ VILLANUEVA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "YAZMIN HERNÁNDEZ BALDERAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "YOLANDA LIZBETH BAUTISTA ARAGÓN", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIA GUADALUPE DOMINGUEZ DELGADO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SARISH DEL REAL ORDOÑEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALMA AZUCENA SEGURA CHAMA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ANA ELENA MARTIN AGUILAR", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "CRISTOBAL DIAZ GOMEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EDGAR VARELA SANTOYO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EDITH GARCÍA LUNA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GUILLERMO MORENO FLORES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GUSTAVO FLORENCIO CORTES MARTINEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "HECTOR RODRIGUEZ NAVARRO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ITZIA VERDUZCO FLORES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JORGE ANTONIO MACÍAS MILLÁN", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUIS ARTURO CARDOSO APARICIO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUIS ENRIQUE SOTO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARGARITA CAMPUZANO BUENROSTRO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MAYRA CRISTINA GALEANA HERNANDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "OMAR SPENCER AGUILAR REYES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "OSVALDO HERNANDEZ FLORES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ROMMEL IVAN RODRIGUEZ SIMENTAL", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIO EDUARDO ALONSO CALAMACO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DAVID DÁVILA DUPONT", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DIONE AGUILAR Y MÉNDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GERARDO AMARANTE DE LEÓN", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GUADALUPE EVARISTO CEDILLO SALAZAR", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MAURICIO ANTUAN CANAVATI MARCOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "AMANCIO GATICA PEREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "CARMEN AGUILAR JIMENEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE GUSTAVO NUÑEZ CARRILLO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SALVADOR MACIAS DÍAZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DAVID ACOSTA GUTIÉRREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LEOPOLDO ABRAHAM LUGO ALFEREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARINEE TORRES AGUILAR", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MIJAEL TOIBER LEVY", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EMILIO GÁMEZ UGALDE", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JAIME ARTURO GUEL", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JUAN FRANCISCO GONZALEZ GUERRERO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ERICK SALADO RAMIREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JESUS RICO GUTIERREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIA DEL ROSARIO ESTRADA FALCON", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GUILLERMO GOCHER DAMIÁN", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JAIME NAVARRETE ALEMÁN", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSAFAT RAMIREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LEONARDO VERDUZCO RODRIGUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "NORMA CLAUDIA ARÉCHIGA RAMOS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "FROYLAN LÓPEZ LÓPEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "CLAUDIA LORENA URZUA FLORES", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ELIA NALLELY BARRIENTOS LUNA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MARÍA CRISTINA AGUILAR MARTÍNEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ADRIAN CRAVIOTO VILLANUEVA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ALBERTO OLAYA VARGAS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ALBERTO VILLALOBOS PRIETO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ALEJANDRO NOGUEZ RAMOS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ALLAN LEGASPI SAUTER", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ALMA MARIA MEDRANO HERNANDEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ALVARO AGUAYO GONZÁLEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ALVARO LEZID PADILLA RODRIGUEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ANTONIO GOMEZ PEDRAZA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ANTONIO MAFFUZ AZIZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "CARLOLS DANIEL ROBLES VIDAL", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "CARLOS ARTURO GONZÁLEZ NÚÑEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "CHRISTIAN PATRICIO CAMACHO LIMAS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "CLAUDIO RENE MONTESDEOCA ORELLANA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "CONNIE ZURATZI DENEKEN HERNÁNDEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "CONSUELO IRENE GUTIERREZ COLIN", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "DAGOBERTO MOLINA POLO LÓPEZ DE CÁRDENAS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "DANIELA SHVEID GERSON", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "DANIELLA GOMEZ PUE", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "DAVID EDUARDO MUÑOZ GONZALEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "DIANA ALEJANDRA VILLEGAS OSORNO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ELIAS RESCALA BACA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ELIZABETH SANCHEZ VALLE", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ENRIQUE GOMEZ MORALES", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ERIKA BETZABE RUIZ GARCIA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ERNESTO JOSE ZEPEDA CASTILLA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ERNESTO R. SANCHEZ FORGACH", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ESMERALDA ROMERO BAÑUELOS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "FERNANDO CORDERA GONZALEZ DE COSIO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "FERNANDO PEREZ ZINCER", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "GABRIEL SANTIAGO CONCHA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "GABRIELA OLIVIA REGALADO PORRAS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "GEOVANI AMADOR GARCIA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "GERARDO MIRANDA DEVORA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "GUILLERMO MANUEL OLIVARES BELTRÁN", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "HORACIO SUÁREZ DEL PUERTO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "IRMA SOLDEVILLA GALLARDO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "IRVING JAVIER MEJIA HERNANDEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JAIME SHALKOW KLINCOVSTEIN.", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JANISSE KERSHENOVICH GERSSON", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JESUS MIGUEL LAZARO LEÓN", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JORGE ARTURO ALATORRE ALEXANDER", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JOSE ANTONIO POSADA TORRES", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JOSE FABIAN MARTINEZ HERRERA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JOSE GABRIEL CHAVEZ SANCHEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JUAN ALBERTO SERRANO OLVERA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JUAN MANUEL STETA OROZCO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "LEOPOLDO GUZMAN NAVARRO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "LUIS ANTONIO LARA MEJIA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "LUIS ANTONIO MEILLON GARCIA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "LUISA FERNANDA MARISCAL MENDIZABAL", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MANUEL ACUÑA TOVAR", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MANUEL MAGALLANES", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MANUEL ROBERTO MORALES POLANCO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MARIA ANDREA BARBERO IBARROLA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MARÍA DOLORES DE LA MATA MOYA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MARYTERE HERRERA MARTINEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MELANIA ABREU GONZALEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MIGUEL CORRES MOLINA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MILAGROS PÉREZ QUINTANILLA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MONICA ISABEL MENESES MEDINA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "NICOLE MARIE ÍÑIGUEZ ARIZA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "OTONIEL LOPEZ RIVEROL", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "PATRICIA GRETHER GONZALEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "PAULA ANEL CABRERA GALEANA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "RAQUEL GERSON CWILICH", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ROBERTO ALFARO LARA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ROBERTO ENRIQUE HERNANDEZ PEÑA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ROBERTO RIVERA LUNA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ROBIN JENNIFER SHAW DULIN", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ROCIO DEL SOCORRO CARDENAS CARDOS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "RODRIGO YAHEL ADAME MORENO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "RONNY KERSHENOVICH SEFCHOVICH", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "SAMUEL RIVERA RIVERA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "SILVIA NATALIA LOPEZ HERNANDEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "SILVIA PATRICIA VILLAREAL COLIN", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "SUSANA MONROY SANTOYO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "TALIA WEGMAN OSTROSKY", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "VANESSA ROSAS CAMARGO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "YADIRA BERENICE MELCHOR VIDAL", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "YAZMIN CAROLINA BLANCO VAZQUEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "YVETTE NEME YUNES", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ALFONSO PEREZ BAÑUELOS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ANA PAULINA MELENDEZ FERNANDEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "CARLOS DANIEL LEVER ROSAS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "DORA GILDA MAYEN MOLINA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "GABRIEL TELLEZ TREVILLA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "GABRIELA AZUCENA ARENAS PEREZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "GILDA SOFIA GARZA MAYEN", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JORGE ENRIQUE MONGES JONES", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JORGE LUIS CORTES RUBIO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JORGE MANUEL RUANO AGUILAR", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JOSE FRANCISCO GALLEGOS HERNANDEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "CESAR DANIEL HERNANDEZ MENDEZ", "KAM": "SIN ASIGNAR", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE GABRIEL PEÑALOZA GONZALEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JOSE RODRIGO ESPINOSA FERNANDEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JUAN ALEJANDRO SILVA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "KARLA SUSANA MARTIN TELLEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MARCO ANTONIO DE LA ROSA ABAROA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MARIO CUELLAR HUBBE", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "PABLO GALLO STETA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "RAFAEL BRICEÑO HERNANDEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "RAFAEL PADILLA LONGORIA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "RODRIGO ARRANGOIZ MAJUL", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "SERGIO CARLOS RODRIGUEZ BAHENA", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "SERGIO TORRES VARGAS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "DIEGO JORGE", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ERNESTO MORENO SALAS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ANDREA CASTRO SÁNCHEZ", "KAM": "MARYMAR", "TELEFONO KAM": "5543401015"}, {"Doctor": "FRANCISCO JAVIER ALVARADO VILLAREAL", "KAM": "MARYMAR", "TELEFONO KAM": "5543401015"}, {"Doctor": "FRANCISCO GALLEGOS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JOSE GADU CAMPOS SALCEDO", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MAXWELL AVILES RODRIGUEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ELVIRA GÓMEZ GÓMEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "MARICELA GARCIA GARCÉS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "SAUL CAMPOS GOMEZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "GISELA NIEVES HERNÁNDEZ RUIZ", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "JUAN LORENZO ESPINO VILLALOBOS", "KAM": "ANGEL", "TELEFONO KAM": "5579681460"}, {"Doctor": "ANTONIO ROLON PADILLA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ARMANDO RAMIREZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "FROYLAN LOPEZ LOPEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JESUS ELVIS CABRERA LUVIANO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JORGE ARMANDO CASTELAN PEDRAZA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JORGE MAYORGA ACUÑA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSE JUAN RAMIREZ JAIME", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ALICIA GUTIERREZ MATA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "BRIZIO MORENO JAIME", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "CARLOS ALBERTO RAMIREZ ALVARADO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "CARLOS RAMÍREZ ALVARADO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "DANIEL CAPDEVILLE GARCIA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "DANIEL CAPDEVILLE GARCÍA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "DANIEL PÉREZ CERVANTES", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "DAVID CAZARES SANCHEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "DAVID CÁZAREZ SÁNCHEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "DAVID CUEVAS QUEZADA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "DAVID SUÁREZ GARCÍA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "FERNANDO SALDÍVAR GALINDO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JHONATAN BUENO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSE AGUIRRE TRIGUERO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSE ANTONIO TREJO PANTOJA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSÉ LUIS GONZÁLEZ TRUJILLO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSÉ LUIS GONZÁLEZ TRUJILLO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "LETICIA VÁZQUEZ CORTÉS", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "LUIS JONATHAN BUENO ROSARIO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "MA ISABEL ENRÍQUEZ ACEVES", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ROBERTO KURI EXSOME", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ROBERTO KURI EXSOME", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "SALVADOR NAVARRO HERNANDEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ADRIAN GOMEZ GOMEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ALBERTO ALVARADO MIRANDA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ALEJANDRO CASTILLO GALEAZZI", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ALEJANDRO CASTILLO GALEAZZI", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ALFREDO AVILA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ALMA ROSA LÓPEZ MARISCAL", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ANA GRACIELA PUEBLA MORA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ANA OLIVIA CORTES FLORES", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ANA OLIVIA CORTÉS FLORES", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "ATZIRI AIDEE MADERO CASTRO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "BENITO SANCHEZ LLAMAS", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "BENITO SÁNCHEZ LLAMAS", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "CARLOS ALBERTO RONQUILLO CARREÓN", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "CARLOS ALBERTO RONQUILLO CARREÓN", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "CARLOS ZULOAGA FERNÁNDEZ DEL VALLE", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "CITLALI LÓPEZ ARCIGA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "DANIEL ALEJANDRO GARCÍA PADILLA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "DANIEL ALEJANDRO GARCÍA PADILLA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "DAVID PONCE HERRERA", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "DIEGO A. DÍAZ GARCÍA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "DIEGO ARMANDO DÍAZ GARCÍA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "EDER ARAIZA ALVARADO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "EDUARDO BARRAGAN CURIEL", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "EDWARD MORGAN OCHOA", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "EFRAÍN SALAS GONZÁLEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "EMILIO MURILLO RAMÍREZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "EMMANUEL DE LA MORA JIMÉNEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ERIKA SUSANA BARBOSA AVALOS", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "GILBERTO MORGAN VILLELA", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "IGNACIO MARISCAL RAMÍREZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "IGNACIO MIGUEL FUENTES MENDEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ISAAC LUNA BENITEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JAIME CORONA RIVERA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JAIME CORONA RIVERA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JORGE EMILIO ARCH FERRER", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JORGE EMILIO ARCH FERRER", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSE ANTONIO ACEVEDO DELGADO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSE DE JESUS CURIEL VALDES", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSÉ FRANCISCO ALEXANDER MEZA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSE JOB LAGUNES MUNOZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSÉ JOB LAGUNES MUÑOZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSÉ ROGELIO GONZÁLEZ RAMÍREZ BENFIELD", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "JUAN CARLOS VÁZQUEZ LIMÓN", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "KATHIA SUSANA ZAMUDIO OSUNA", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "KATHIA SUSANA ZAMUDIO OSUNA", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "LEONORA VALDEZ ROJAS", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "LIDO JOSÉ MANUEL GÓMEZ GLEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "LUIS ALBERTO GARCIA GONZALEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "MARCOS FABIAN MONZALVO HERNANDEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "MARIA DOLORES SALAS AGUIRRE", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "MARÍA GUADALUPE VILLA GRAJEDA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "MARIA PAZ COVARRUBIAS RODRIGUEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "MIGUEL ÁNGEL ARAUJO MELENDEZ", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "OMAR CHAVEZ SANCHEZ", "KAM": "CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "OSCAR ARMANDO MELHADO ORELLANA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "OSCAR ARMANDO MELHADO ORELLANA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "PEDRO ROBLES NOLAZCO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "RENÉ GÓMEZ CERDA", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "RICARDO CAVAZOS GARCÍA", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "RICARDO CAVAZOS GARCÍA", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "ROSARIO MARISOL QUINTERO SOLIS", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "XIMENA FERNANDEZ SOTO", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSE LUIS ZARAGOZA H.", "KAM": "JOSÉ FRANCISCO / CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "VICTOR MANUEL CORREA SANTILLAN", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "GUADALUPE MONSERRAT GUTIERREZ MOTA", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "JUAN ANTONIO DELGADO VÁZQUEZ", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "RAMSÉS ALBERTO CASTILLO CHIQUETE", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "FERNANDO ZAZUETA LEÓN QUINTERO", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "TOMAS PINEDA RAZO", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "JOSÉ LENIN BELTRÁN", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "HÉCTOR BENITEZ ARROYO", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "JACQUELINE H DIAZ GARZA", "KAM": "JOSÉ FRANCISCO", "TELEFONO KAM": "5554360130"}, {"Doctor": "SERGIO ALEJANDRO ARREOLA", "KAM": "CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "MIGUEL ANGEL URIBE", "KAM": "CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "ERICK FLORES OROZCO", "KAM": "CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "SOCORRRO RÍOS MERCADO", "KAM": "CLAUDIA", "TELEFONO KAM": "5554360130"}, {"Doctor": "AARON GONZALEZ ENCISO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ABIGAIL SAMOAYA MATEOS SORIA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALBERTO GONZALEZ AGUILAR", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALBERTO MITSUO LEON TAKAHASHI", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALBERTO MONROY CHARGOY", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALEJANDRA ARMENGOL ALONSO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALFONSO CERVERA UBIERNA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALFONSO TORRES LOBATON", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ANA MARIA ZEMPOALTECA LOPEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ANGELICA CONCEPCIÓN  CRUZ CADENA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ANTONIO ALFEIRAN RUIZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ANTONIO VELAZQUEZ GONZÁLEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ARACELI RIVERA SANTIAGO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ARIADNA ESTELA  GONZALEZ DEL ANGEL", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ARMANDO BERNANDO MARTINEZ AVALOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ARMEN STANKOV DRAGAN", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ARTURO PABEL MIRANDA AGUIRRE", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "CARLO EGYSTO CICERO ONETO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "CARLOS ARANDA FLORES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "CARLOS EDUARDO QUINTERO RODRIGUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "CHRISTIAN HAYDEE FLORES BALCAZAR", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DAN GREEN REENER", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DANIEL ABELARDO LOPEZ VALLEJO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DANIEL MOTOLA KUBA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DAVID FRANCISCO CANTU DE LEON", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DAVID ORTA CORTES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DEBORAH MARIA MARTINEZ BAÑOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DENISE ACUÑA GONZALEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DIANA FABIOLA FLORES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DIEGO OSORIO PEREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "DOLORES GALLARDO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EDER A ARANGO BRAVO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EDUARDO EMIR CERVERA CEBALLOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EDUARDO JORGE BAÑOS RODRIGUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ELEAZAR OMAR MACEDO LOPEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ELIA IXEL APODACA CHAVEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ELIZABETH ESCOBAR ARRIAGA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EMILIO CONDE", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ERIC ORTIZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EUCARIO LEON RODRIGUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "EVA RUVALCABA LIMON", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FEDERICO MALDONADO MAGOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FERNANDO ALDACO SARVIDE", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FERNANDO CANDANEDO GONZALEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FERNANDO ENRIQUE MAINEROL RATCHEOLUS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FIDEL DAVID HUITZIL MELENDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FLAVIA MORALES VASQUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FLOR MARIA ARMILLAS CANSECO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FRANCISCO JAVIER GOMEZ-PEDROSO REA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FRANCISCO JAVIER OCHOA CARRILLO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FRANCISCO LOPEZ SACHINAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "FRANCO KRAKAUR GARCÍA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GABRIEL ORLANDO GARCIA ACEVEDO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GABRIEL PACHECO JUAREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GABRIELA ALAMILLA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GABRIELA ALVARADO LUNA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GEORGINA GARNICA JALIFFE", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GERMAN CALDERILLO CRUZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GREDEL PORTELA RUBIO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GREGORIO QUINTERO BEULO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GUILLERMO FABIAN SILVA ESCOBAR", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GUILLERMO MARTOS RAMIREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "GUSTAVO SEBASTIAN ESCOBAR ALFARO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "HAYDEÉ CRISTINA VERDUZCO AGUIRRE", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "HEBER TOMAS REYES GARCIA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "HECTOR DE LA MORA MOLINA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "HECTOR MARTINEZ SAID", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "HORACIO NOÉ LOPEZ BASAVE", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "IDELFONSO ROBERTO DE LA PEÑA LOPEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ILEANA MCKINNEY NOVELO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ITZEL VELA SARMIENTO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "IVAN EUDALDO DIAZ MENESES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JAIME ALONSO RESENDIZ COLOSIA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JAVIER KELLY GARCIA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JAVIER LOPEZ GOMEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JAVIER MELCHOR RUAN", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JAZMÍN FIGUEROA BADILLO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JERONIMO RAFAEL RODRIGUEZ CID", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JONATHAN RUBEN CEDILLO RODRIGUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JORGE ADAN ALEGRÍA BAÑOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JORGE ALBERTO ROBLES AVIÑA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JORGE ALEJANDRO CASTAÑEDA ÁVILA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JORGE BERMUDEZ LUGO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JORGE LUIS MARTINEZ TLAHUEL", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JORGE MARTINEZ CEDILLO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE ADALBERTO TORIZ HERNANDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE ALBERTO ABREGO VASQUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE ANTONIO BAHENA GONZALEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE FRANCISCO CORONA CRUZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE LUIS AGUILAR PONCE", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE MANUEL RUIZ MORALES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSE ROBERTO JUAREZ DIAZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JOSEPH XAVIER LOPEZ KARKPOVITCH", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JUAN ALBERTO TENORIO TORRES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JUAN ANTONIO MATUS SANTOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JUAN CARLOS HERNANDEZ FONSECA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JUAN MANUEL VARELA GAYOL", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JUAN WOLFGANG ZINZER SIERRA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "JUSTO GONZALO MILAN REVOLLO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "KARLA BELEN MOLINA TABAREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "KUAUHYAMA LUNA ORTÍZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LAURA GABRIELA FLORES PEÑA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LENNY NADIA GALLARDO ALVARADO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LETICIA ELIZABETH MOTA GARDUÑO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LIZ NAVA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUCELY DEL CARMEN CETINA PEREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUIS ANTONIO CABRERA MIRANDA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUIS ARTURO HERNANDEZ LOPEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUIS CRUZ BENITEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUIS ENRIQUE JUAREZ VILLEGAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUIS FERNANDO PEREZ JACOBO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUIS GERARDO MOTA CIENFUEGOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "LUZ MARIA HINOJOSA GARCIA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MA DELIA PEREZ MONTIEL", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MANUEL ALONSO VILLEGAS MARTINEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MANUEL GONZALEZ REYES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARA NUÑEZ TOSCANO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARÍA DEL MAR GARCIA ORTEGA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIA FATIMA CHILACA ROSAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIA GUADLUPE CERVANTES SANCHEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIA TERESA BOURLON DE LO RÍOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARIO SANCHEZ CORZO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARLID CRUZ RAMOS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MARTHA GABRIELA TAVERA RODRIGUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MICHEL HERNANDEZ VALADEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MIGUEL ANGEL ALVAREZ AVITIA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MIGUEL ANGEL LOPEZ VALLE", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MIGUEL ANGEL TLETLEPANTZIN APARTADO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MIGUEL ARNOLDO FARIAS ALARCON", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "MYRNA GLORIA CANDELARIA HERNÁNDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "NEREIDA ESPARZA ARIAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "NICOLAS RICARDO DE JESUS SANCHEZ CASAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "NIDIA  PAULINA ZAPATA CANTO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "NORA SOBREVILLA MORENO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "NORMA CANDELARIA LOPEZ SANTIAGO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "NOVELTHYS VELASCO CORTES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ODILON FELIX QUIJANO CASTRO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "OMAR DE LEON PACHECO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "OMAR FRANCISCO CORONEL AYALA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "OMAR MACEDO PEREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "OSCAR GERARDO ARRIETA RODRIGUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "OSVALDO QUIROZ SANDOVAL", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "PATRICIA CORTES ESTEBAN", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "PATRICIO AZAOLA ESPINOZA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "PEDRO DE JESUS SOBREVILLA CALVO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "RAFAEL HURTADO MONROY", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "RAFAEL VAZQUEZ ROMO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "RAMIRO GARCIA ORTIZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "RAUL ARTGUZMAN TRIGUEROS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ROBERTO DE LA PENA LOPEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ROCIO CRYSTAL GRAJALES ALVAREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "RODRIGO DIAZ MACHORRO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ROGELIO MARTINEZ MACIAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ROSA HIMELDA ARELLANO BERNAL", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "RUBEN CORTES GONZALEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SAMANTHA LOPEZ RAMIREZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SANTA MARICELA ORTIZ ZEPEDA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SANTIAGO ALEJANDRO CANO CANCELA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SANTOS GILBERTO SOTO GERMES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SARA OLIVIA RAMOS ROMERO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SEBASTIAN GARCÍA HERRERA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SERGIO AGUILAR VILLANUEVA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SERGIO CESAR LOPEZ GARCI A", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SERGIO RODRIGUEZ-CUEVAS", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "SERGIO YASPIK FLORES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "TANIA ÁLVAREZ DOMÍNGUEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "WENDY ROSANGELA MARTINEZ TORRES", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "WENDY ROSSEMARY MUÑOZ MONTAÑO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "YAMILE TORRES JASSO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "YANIN CHAVARRI GUERRA", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ZULEIMA GARCÍA NIETO", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "NORA HILDA CHÁVEZ HERNÁNDEZ", "KAM": "ANDREA", "TELEFONO KAM": "5579681304"}, {"Doctor": "ALEJANDRO MARTINEZ RUEDA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "CARLOS ROBERTO LUGO ESCALANTE", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "DIEGO ALFONSO BALLESTEROS PINO", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "FERNANDO JAVIER VILLALOBOS PEÑA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "IVAN SALGADO", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JENNIFER RAMIREZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JESUS ALICIA ACOSTA ESPINOZA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JORGE ALBERTO GUADARRAMA OROZCO", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "MARCELINO MORALES RIVERA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "DANIELA HERNANDEZ LARA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "DAVID FUENTES MEDINA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ENRIQUE JOSE ZAMUDIO LOZOYA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "FELIPE DE JESÚS ANCHONDO ORTEGA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "FLOR DE THE BUSTAMANTE VALLES", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "IVONNE SALAS", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JESSICA SALAZAR", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JORGE SAID GARCÍA BAUTISTA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JUAN ADNAN CRUZ VALENZUELA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "LUIS JAVIER BARAJAS FIGUEROA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "MARCELINO RAMÍREZ MARQUEZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "MARIA HELENA VILLALOBOS GOMEZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "RAMIRO MAGANA SERRANO", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "RAUL GERARDO RAMIREZ MEDINA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ALMA GEORGINA PALACIOS MARTINEZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ALMA MAGDALENA ASTORGA RAMOS", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ELISEO EMMANUEL JUÁREZ ZUÑIGA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "HIRAM JOSUE GRIMALDO ROQUE", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "MICHEL BONIFANT", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ALAN LEDIF REYES MONDRAGÓN", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ALAN BURGUETE TORRES", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ALEJANDRO DE LEON CRUZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ALETHIA ALVAREZ CANO", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ALVARO BARBOSA-QUINTANA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ANGEL AZAEL LÓPEZ GALINDO", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "CARLOS AUGUSTO GUTIERREZ FLORES", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "CARLOS EDUARDO SALAZAR MEJIA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "CESAR GONZALEZ DE LEON", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "CESAR SALDIVAR MORENO", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "CINDY AIDEE NÁJERA MUÑOZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "CYNTHIA VILLARREAL", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "DANIEL VALENCIA MERCADO", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "DANIELA VAZQUEZ JUAREZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "EDIO LLERENA HERNANDEZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "EDUARDO ALBERTO GUZMAN HUERTA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "GABRIELA SOFIA GOMEZ MACIAS", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "GERARDO CARDENAS", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "GERARDO DAVID AMARANTE DE LEON", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "HORACIO DECANINI ARCAUTE", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JACKELINE GRACE LARA CAMPOS", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JAIME J. TAMEZ SALAZAR", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JESÚS ALBERTO LIMÓN RODRÍGUEZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JORGE ALBERTO HERNÁNDEZ SALAZAR", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JORGE LUIS MARTINEZ RODRIGUEZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JOSE LUIS GUZMAN MURGIA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JOSÉ LUIS VELA GONZALEZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "LIGIA LARRALDE", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "LUIS ANTONIO CANCEL TREVIÑO", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "MANUEL ISMAEL GONZÁLEZ GERONIZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "MARÍA LUISA ROMERO LAGUNES", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "OMAR ALEJANDRO ZAYAS VILLANUEVA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "OMAR PEÑA CURIEL", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "OSCAR VIDAL GUTIERREZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "RAUL GARZA GARZA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ROGELIO LOZANO GALVAN", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ROLANDO MARTINEZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "RUBI JANDAY NAJERA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "SERVANDO CARDONA HUERTA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "VICTOR MANUEL OYERVIDES JUAREZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "YURIDIA ALVARADO BERNAL", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "ENRIQUE AVILA MONTEVERDE", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "JUAN DE DIOS PÉREZ VILLEGAS", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "LAURA PEREZ MICHEL", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "MINOR CORDERO B.", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "GENOVEVA OCHOA", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "OSCAR ALEJANDRO GOMEZ", "KAM": "NEREIDA", "TELEFONO KAM": "5580559686"}, {"Doctor": "IVÁN ROMARICO GONZÁLEZ ESPINOZA", "KAM": "INPLANT PUEBLA", "TELEFONO KAM": "5551903380"}];
const ASEG = ["PARTICULAR (PAGO DE BOLSILLO)","ALLIANZ","AXA SEGUROS","BANCO DEL BIENESTAR","BANCOMEXT","BANJÉRCITO","BANRURAL","BEST DOCTORS CLAIMS CENTER","BUPA MEXICO COMPAÑÍA DE SEGUROS","CNBV","GNP","HSBC JUBILADOS Y PENSIONADOS","HSBC-EDPM (ACTIVOS)","INDEP","LUZ Y FUERZA JUBILADOS","MAPFRE","METLIFE","NAFIN //NACIONAL FINANCIERRA","OMA ATLANTIS","PAN-AMERICAN","PLAN SEGURO","PREVEM SEGUROS","PROSESO","PUNTO PEN","SEGUROS ATLAS","SEGUROS BANORTE","SEGUROS INBURS","SEGUROS MONTERREY NEW YORK LIFE","SEGUROS SURA","SEGUROS VE POR MÁS","SHF","SOLUGLOB IKON","ZURICH","VUMI"];

// === Utilidades y estado ===
const fmt = n => (Number(n)||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'});
const dom = sel => document.querySelector(sel);

// Teléfonos por listado (según CONFIG)
const TEL = {"gestion_nomad":"55 5255 8403","gestion_comercial":"55 43 40 10 15","gnp":"55 79 68 13 04","dra_genoveva":"55 79 68 13 04"};

let DATA = {pruebas:[]};

// === Inicialización ===
function setFechas() {
  const emision = dom('#fechaEmision');
  const validez = dom('#fechaValidez');
  const hoy = new Date();

  // Obtener fecha local (YYYY-MM-DD)
  const yyyy = hoy.getFullYear();
  const mm = String(hoy.getMonth() + 1).padStart(2, '0');
  const dd = String(hoy.getDate()).padStart(2, '0');
  const fechaLocal = `${yyyy}-${mm}-${dd}`;

  emision.value = fechaLocal;

  // Validez +15 días
  const validezDate = new Date(hoy);
  validezDate.setDate(hoy.getDate() + 15);
  const yyyy2 = validezDate.getFullYear();
  const mm2 = String(validezDate.getMonth() + 1).padStart(2, '0');
  const dd2 = String(validezDate.getDate()).padStart(2, '0');
  validez.value = `${yyyy2}-${mm2}-${dd2}`;
}

function actualizarTelefonoPorListado(listado) {
  dom('#telefono').textContent = "Teléfono: " + (TEL[listado] || "");
}

function poblarAseguradoras() {
  const selA = dom('#aseguradora');
  selA.innerHTML = '<option value="">Selecciona…</option>' + ASEG.map(a=>`<option value="${a}">${a}</option>`).join('');
}

function poblarMedicos(lista) {
  const selMed = dom('#medico');
  selMed.innerHTML = '<option value="">Selecciona…</option>' + 
    (lista||MEDICOS).map(m=>`<option value="${m["Doctor"]}">${m["Doctor"]}</option>`).join('');
}

function setupBuscadores() {
  const inputMed = dom('#buscarMedico');
  const selMed = dom('#medico');
  const inputKam = dom('#buscarKam');
  const inputAseg = dom('#buscarAseg');
  const selA = dom('#aseguradora');

  // Buscar médico
  inputMed.addEventListener('input', ()=>{
    const q = (inputMed.value||'').toLowerCase();
    const filtrados = MEDICOS.filter(m=>m["Doctor"].toLowerCase().includes(q));
    poblarMedicos(filtrados);
  });

  // Selección de médico → KAM
  selMed.addEventListener('change', ()=>{
    const m = MEDICOS.find(x=>x["Doctor"]===selMed.value);
    dom('#kam').value = m ? (m["KAM"] || '') : '';
  });

  // Buscar por KAM
  inputKam.addEventListener('input', ()=>{
    const q = (inputKam.value||'').toLowerCase();
    const filtrados = MEDICOS.filter(m=>(m["KAM"]||'').toLowerCase().includes(q));
    poblarMedicos(filtrados);
  });

  // Buscar aseguradora
  inputAseg.addEventListener('input', ()=>{
    const q = (inputAseg.value||'').toLowerCase();
    const filtradas = ASEG.filter(a => a.toLowerCase().includes(q));
    selA.innerHTML = '<option value="">Selecciona…</option>' + filtradas.map(a=>`<option value="${a}">${a}</option>`).join('');
  });
}

function cargarListado(listado) {
  DATA = {
    pruebas: DATASETS[listado] || [],
    biomarcadores: (BIOMARCADORES[listado] || [])
  };
  poblarPruebas();
  poblarBiomarcadores();
  actualizarTelefonoPorListado(listado);
}

function poblarPruebas() {
  const sel = dom('#selPrueba');
  const buscar = dom('#buscarPrueba');
  const orden = dom('#ordenPruebas');
  let items = [...(DATA.pruebas||[])];

  function render() {
    let q = (buscar.value||'').toLowerCase();
    let filtered = items.filter(p => (p.nombre||'').toLowerCase().includes(q));
    if (orden.value==='precio') filtered.sort((a,b)=>(b.precio||0)-(a.precio||0));
    else filtered.sort((a,b)=>(a.nombre||'').localeCompare(b.nombre||'', 'es'));
    sel.innerHTML = filtered.map(p=>`<option value="${p.nombre}" data-precio="${p.precio||0}">${p.nombre} — ${fmt(p.precio||0)}`)
      .join('');
  }
  buscar.addEventListener('input', render);
  orden.addEventListener('change', render);
  render();
}

function addLinea(nombre, precio, cant){
  const tb = dom('#tablaPruebas tbody');
  const row = document.createElement('tr');
  const subtotal = (precio||0) * (cant||1);
  row.innerHTML = `
    <td>${nombre}</td>
    <td>${cant}</td>
    <td>${fmt(precio||0)}</td>
    <td>${fmt(subtotal)} </td>
    <td><button class="btn-eliminar">Eliminar</button></td>`;
  row.querySelector('.btn-eliminar').addEventListener('click', ()=>{ 
    row.remove(); 
    calcTotales(); 
    updateNormalMatchOption();
  });
  tb.appendChild(row);
  calcTotales();
  updateNormalMatchOption();
}


function calcTotales(){
  let subtotal = 0;
  document.querySelectorAll('#tablaPruebas tbody tr').forEach(tr=>{
    const val = tr.children[3].textContent.replace(/[^0-9.,-]/g,'').replace(',','');
    subtotal += Number(val);
  });
  const iva = subtotal * 0.16;
  dom('#subtotal').textContent = fmt(subtotal);
  dom('#iva').textContent = fmt(iva);
  dom('#total').textContent = fmt(subtotal + iva);
}

function setupAgregar(){
  dom('#addPrueba').addEventListener('click', ()=>{
    const sel = dom('#selPrueba');
    if(!sel.value) return;
    const precio = Number(sel.options[sel.selectedIndex].dataset.precio||0);
    const cant = Number(dom('#cantPrueba').value||1);
    addLinea(sel.value, precio, cant);
  });
}


function poblarBiomarcadores(){
  const sel = dom('#selBiomarcador');
  if(!sel) return;
  const items = (DATA.biomarcadores||[]);
  sel.innerHTML = items.map(b=>`<option value="${b.nombre}" data-precio="${b.precio||0}">${b.nombre} — ${fmt(b.precio||0)}</option>`).join('');
  updateNormalMatchOption();
}


function updateNormalMatchOption(){
  const sel = dom('#selBiomarcador');
  if(!sel) return;

  const hasTempusXtXr = Array.from(document.querySelectorAll('#tablaPruebas tbody tr td:first-child'))
    .some(td => (td.textContent||'').replace(/\s+/g,' ').trim().toLowerCase() === 'tempus xt + xr');

  const opts = Array.from(sel.options);
  const hasOpt = opts.some(o => (o.value||'').trim().toLowerCase() === 'normal match');

  if(hasTempusXtXr && !hasOpt){
    const opt = document.createElement('option');
    opt.value = 'NORMAL MATCH';
    opt.setAttribute('data-precio','0');
    opt.textContent = `NORMAL MATCH — ${fmt(0)}`;
    sel.appendChild(opt);
  }else if(!hasTempusXtXr && hasOpt){
    opts.forEach(o=>{
      if((o.value||'').trim().toLowerCase() === 'normal match') o.remove();
    });
  }
}


function setupBiomarcadores(){
  const btn = dom('#addBiomarcador');
  const sel = dom('#selBiomarcador');
  if(!btn || !sel) return;
  btn.addEventListener('click', ()=>{
    const opt = sel.selectedOptions[0];
    if(!opt) return;
    const nombre = opt.value;
    let precio = Number(opt.getAttribute('data-precio')||0);

    // Regla especial: si hay cualquier prueba "Foundation" en la tabla y se agrega este biomarcador,
    // forzar el precio a $5,000.00 (sin afectar otros rubros)
    const tieneFoundation = Array.from(document.querySelectorAll('#tablaPruebas tbody tr td:first-child'))
      .some(td => (td.textContent||'').toLowerCase().includes('foundation'));
    if(tieneFoundation && (nombre||'').trim().toLowerCase() === 'pdl1 sp263 y 22c3'.toLowerCase()){
      precio = 5000.00;
    }

    // Regla especial: NORMAL MATCH solo aplica si está seleccionada la prueba "Tempus xT + xR"
    const tieneTempusXtXr = Array.from(document.querySelectorAll('#tablaPruebas tbody tr td:first-child'))
      .some(td => (td.textContent||'').replace(/\s+/g,' ').trim().toLowerCase() === 'tempus xt + xr');
    if((nombre||'').trim().toLowerCase() === 'normal match'){
      if(!tieneTempusXtXr){
        alert('NORMAL MATCH solo aplica para Tempus xT + xR.');
        return;
      }
      precio = 0;
    }

    addLinea(nombre, precio, 1);
  });
}

function setupListado(){
  const listado = dom('#listado');
  listado.addEventListener('change', ()=> cargarListado(listado.value));
  cargarListado(listado.value);
}


function setupPDF(){
  const btn = document.getElementById('btnPDF');
  btn.addEventListener('click', async ()=>{
    const pacienteRaw = (document.getElementById("paciente").value || "SinNombre").trim();
    const paciente = pacienteRaw.replace(/\s+/g,""); // remove spaces
    let fechaEmision = document.getElementById("fechaEmision").value;
    if(!fechaEmision){
      const d=new Date();
      fechaEmision = d.getDate()+"-"+(d.getMonth()+1)+"-"+d.getFullYear();
    } else {
      fechaEmision = fechaEmision.replace(/\//g,"-");
    }
    const usuario = localStorage.getItem("usuarioActual") || "nomad";
    const folio = await getNextFolio();
    // Guardar en Firestore si está disponible
    try {
      if (window.saveCotizacion) {
        const payload = getCotizacionPayloadNomad(folio);
        window.saveCotizacion(payload);
      }
    } catch (e) {
      console.warn('No se pudo guardar la cotización en Firebase', e);
    }
    // Mostrar folio en UI antes de captura
    const folioText = document.getElementById("folioText"); if(folioText) folioText.textContent = folio;
    const nombreArchivo = `Nomad-${paciente}-${fechaEmision}-Folio${folio}.pdf`;
const { jsPDF } = window.jspdf;
    const el = document.getElementById('cotizador');
    const canvas = await html2canvas(el, {
      scale: 2,
      useCORS: true,
      onclone: (doc)=> {
        // Ocultar elementos en el DOM clonado para el PDF
        doc.querySelectorAll('.datos, #listado, .linea.derecha.fechas, select, input, button, #ordenPruebas, #buscarPrueba, .btn-eliminar, #btnPDF')
          .forEach(e=>{ e.style.display='none'; });
        // Asegurar que el bloque de fechas para PDF esté visible
        const f = doc.querySelector('.fechas-pdf');
        if (f) f.style.display = 'block';
      }
    });
    const img = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p','mm','a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    let imgWidth = pageWidth;
    let imgHeight = canvas.height * imgWidth / canvas.width;
    if (imgHeight > pageHeight) {
      const ratio = pageHeight / imgHeight;
      imgWidth *= ratio; imgHeight *= ratio;
    }
    const x = (pageWidth - imgWidth)/2;
    pdf.addImage(img, 'PNG', x, 0, imgWidth, imgHeight);
    pdf.save(nombreArchivo);
    await sendToSheet({folio, paciente: pacienteRaw, fecha: fechaEmision, usuario});
  });
}


document.addEventListener('DOMContentLoaded', ()=>{
    setupBiomarcadores();
  setFechas();
  poblarAseguradoras();
  poblarMedicos(MEDICOS);
  setupBuscadores();
  setupListado();
  poblarPruebas();
  setupAgregar();
  setupPDF();
});


// Actualización automática del resumen
function bindResumen() {
  const map = [
    {input: 'nombrePaciente', output: 'rPaciente'},
    {input: 'buscarMedico', output: 'rMedico'},
    {input: 'buscarAseguradora', output: 'rAseguradora'},
    {input: 'buscarKam', output: 'rKam'},
    {input: 'diagnostico', output: 'rDiagnostico'},
    {input: 'fechaProgramacion', output: 'rFecha'}
  ];

  map.forEach(m => {
    const inp = document.getElementById(m.input);
    const out = document.getElementById(m.output);
    if (inp && out) {
      inp.addEventListener('input', e => { out.textContent = e.target.value; });
      inp.addEventListener('change', e => { out.textContent = e.target.value; });
    }
  });
}

document.addEventListener('DOMContentLoaded', bindResumen);


// === Resumen automático ===
function updateResumen() {
  var get = id => document.getElementById(id);
  var val = el => el ? (el.tagName === 'SELECT' ? (el.options[el.selectedIndex] ? el.options[el.selectedIndex].text : el.value) : el.value) : '';
  var set = (id, text) => { var el = get(id); if (el) el.textContent = text || ''; };

  set('rPaciente', val(get('paciente')));
  set('rMedico', val(get('medico')));
  set('rAseguradora', val(get('aseguradora')));
  set('rKam', val(get('kam')));
  set('rDx', val(get('dx')));
  set('rFecha', val(get('fecha')));
}

function bindResumen() {
  ['paciente','medico','aseguradora','kam','dx','fecha','buscarMedico','buscarAseg','buscarKam'].forEach(id=>{
    var el = document.getElementById(id);
    if (!el) return;
    el.addEventListener('input', ()=>{ setTimeout(updateResumen,0); });
    el.addEventListener('change', ()=>{ setTimeout(updateResumen,0); });
  });
  // primera sincronización
  updateResumen();
}

document.addEventListener('DOMContentLoaded', bindResumen);


// === Actualizar fechas en PDF ===
function updateFechasPDF() {
  var em = document.getElementById("fechaEmision");
  var va = document.getElementById("fechaValidez");
  var rp = document.getElementById("realizadoPor");
  if (em) document.getElementById("rFechaEmision").textContent = em.value;
  if (va) document.getElementById("rFechaValidez").textContent = va.value;
  if (rp) document.getElementById("rRealizadoPor").textContent = rp.value;
}

["fechaEmision","fechaValidez","realizadoPor"].forEach(id=>{
  var el = document.getElementById(id);
  if (el) {
    el.addEventListener("input", updateFechasPDF);
    el.addEventListener("change", updateFechasPDF);
  }
});
document.addEventListener("DOMContentLoaded", updateFechasPDF);



// === Login flotante ===
function doLogin() {
  const user = document.getElementById("loginUser").value;
  const pass = document.getElementById("loginPass").value;

  // Lista de usuarios válidos
  const users = {
    "admin": "1234",
    "sanare": "5678",
    "ventas": "abcd",
    "kam1": "kam123",
    "kam2": "kam456"
  };

  if (users[user] && users[user] === pass) {
    document.getElementById("loginOverlay").style.display = "none";
  } else {
    document.getElementById("loginError").style.display = "block";
  }
}

// Revisar sesión al cargar
document.addEventListener("DOMContentLoaded", () => {
  const overlay = document.getElementById("loginOverlay"); if (overlay) overlay.style.display = "flex";
});


// === Add-ons ===
function findMedico(nombre){
  if(!nombre) return null;
  const n = nombre.trim().toLowerCase();
  return MEDICOS.find(m => (m.Doctor||'').toLowerCase() === n) || null;
}
function setKAMAndPhoneFromMedico(nombre){
  const m=findMedico(nombre);
  const kamInput=document.getElementById('kam');
  const tel=document.getElementById('telefono');
  const wa=document.getElementById('waLink');
  if(m){
    if(kamInput) kamInput.value=m.KAM||'';
    if(tel) tel.textContent=m["TELEFONO KAM"]||'';
    if(wa){ let num=(m["TELEFONO KAM"]||'').replace(/[^0-9]/g,''); wa.href=num?`https://wa.me/52${num}`:'#'; }
  }else{
    if(kamInput) kamInput.value='';
    if(tel) tel.textContent='';
    if(wa) wa.href='#';
  }
}
document.getElementById('medico').addEventListener('change',e=>setKAMAndPhoneFromMedico(e.target.value));
// Folio counter
(function(){
  const KEY='nomad_quote_counter';
  let n=parseInt(localStorage.getItem(KEY)||'0'); if(isNaN(n)) n=0;
  n+=1; localStorage.setItem(KEY,n);
  const el=document.getElementById('folioCotizacion');
  if(el) el.textContent=`Nomad-${String(n).padStart(2,'0')}`;
})();
